import os

DATABASE_URL = os.environ["DATABASE_URL"]
TELEGRAM_TOKEN = os.environ["TELEGRAM_TOKEN"]
TELEGRAM_CHAT_ID = os.environ["TELEGRAM_CHAT_ID"]

MIN_PURCHASE = 50_000
CLUSTER_WINDOW_DAYS = 14
GAP_UP_LIMIT = 0.03
STOP_LOSS_PCT = 0.15
HOLD_DAYS = 5
LIMIT_SLIPPAGE = 0.005
